import {User} from './user';

export const USERS: User[] = [
  {  id: '001',
    username: 'HJR',
    password: 'hjr',
    firstName: 'Jridi',
    lastName: 'Hela',
    roleID: 'HR-manager',
    avatar: 'assets/images/avatar hela.png',
    email: 'hela.jridi@thinktank-tunisie.com'},
    {  id: '002',
    username: 'THA',
    password: 'tha',
    firstName: 'Hammami',
    lastName: 'Tarek',
    roleID: 'EMP',
    avatar: 'assets/images/avatar.png',
    email: 'tarek.hamami@thinktank-tunisie.com' },
    {  id: '003',
    username: 'LBJ',
    password: 'lbj',
    firstName: 'Lassaad',
    lastName: 'Ben Jemaa',
    roleID: 'EMP',
    avatar: 'assets/images/lasaad ben jemaa.PNG',
    email: ''},
    {  id: '004',
    username: 'ZS',
    password: 'zs',
    firstName: 'Zied',
    lastName: 'Saidi',
    roleID: 'EMP',
    avatar: 'assets/images/zied saidi.PNG',
    email: ''},
    {  id: '005',
    username: 'MCH',
    password: 'mch',
    firstName: 'Mayssa',
    lastName: 'Chaouachi',
    roleID: 'EMP',
    avatar: 'assets/images/Mayssa.PNG',
    email: ''},
    {  id: '006',
    username: 'ICH',
    password: 'ich',
    firstName: 'Ines',
    lastName: 'Chetouane',
    roleID: 'EMP',
    avatar: 'assets/images/ines chetouane.PNG',
    email: ''},
    {  id: '007',
    username: 'HBA',
    password: 'hba',
    firstName: 'Hafedh',
    lastName: 'Baazouizi',
    roleID: 'EMP',
    avatar: 'assets/images/HAFEDH BAAZOUIZI.PNG',
    email: ''},
    {  id: '008',
    username: 'WKC',
    password: 'wkc',
    firstName: 'Wadiaa',
    lastName: 'Kchouk',
    roleID: 'EMP',
    avatar: 'assets/images/WADIA KCHOUK.PNG',
    email: ''},
    {  id: '009',
    username: 'ZSE',
    password: 'zse',
    firstName: 'Zouheir',
    lastName: 'Sebri',
    roleID: 'EMP',
    avatar: 'assets/images/zouheir sebri.PNG',
    email: ''}
];
